### ISSUE TITLE
Reference to non-existant hsuforum table causing dml error. 

### ISSUE THREAD

**Issue by LoveBug** [open-lms-open-source/moodle-theme_snap#160]
https://github.com/blackboard-open-source/moodle-theme_snap/blob/3c361c796ed5156968f298e169d20279b7f52484/classes/local.php#L1925-L1938

We have found an issue where this code is called when hsuforum is not installed, this causes a crash in the codepath.

**Comment by LoveBug** [comment]
I've created a patch for this issue, found here:  #161

**Comment by dvdcastro** [comment]
Thanks for the patch, we'll review this.

**Comment by peter-lernyx** [comment]
Any news on this? Is this fixed in 3.9?

![grafik](https://user-images.githubusercontent.com/75390480/104007316-0975c200-51a8-11eb-8f4e-df2f90b5a63d.png)

Table 'prefix_.prefix_hsuforum_discussions' doesn't exist
SELECT id, groupid
                          FROM prefix_hsuforum_discussions
                         WHERE id IN (?,?,?)
[array (
  0 => '5',
  1 => '4',
  2 => '1',
)]
Error code: dmlreadexception 
* line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
* line 1247 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 1936 of /theme/snap/classes/local.php: call to mysqli_native_moodle_database->get_records_sql()
* line 1957 of /theme/snap/classes/local.php: call to theme_snap\local::get_groups_ids()
* line 2376 of /theme/snap/classes/local.php: call to theme_snap\local::recent_forum_activity_data()
* line 95 of /theme/snap/classes/webservice/ws_feed.php: call to theme_snap\local::get_feed()
* line 250 of /lib/externallib.php: call to theme_snap\webservice\ws_feed::service()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by peter-lernyx** [comment]
Works for me, thanks LoveBug, Much appreciated.
